[package]
name = "rust-blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]

bincode = "1.3.3" # Specify the compatible version
serde = { version = "1.0", features = ["derive"] }
sled = "0.34"